import { RecordResultProps } from "./types";

export const recordResultsList: RecordResultProps[] = [
  {
    id: 1,
    title: "Alligator",
    artist: "The National",
    year: "2005",
    imageString: "/alligator.webp",
  },
  {
    id: 2,
    title: "Wildflowers",
    artist: "I, the Mountain",
    year: "2025",
    imageString: "/wildflowers.jpg",
  },
  {
    id: 3,
    title: "Abbey Road",
    artist: "The Beatles",
    year: "1969",
    imageString: "/abbeyRoad.webp",
  },
  {
    id: 4,
    title: "By & By",
    artist: "Caamp",
    year: "2019",
    imageString: "/byAndBy.jpg",
  },
  {
    id: 5,
    title: "South of Here",
    artist: "Nathaniel Rateliff & The Night Sweats",
    year: "2024",
    imageString: "/southOfHere.jpg",
  },
  {
    id: 6,
    title: "Midnights",
    artist: "Taylor Swift",
    year: "2022",
    imageString: "/midnights.png",
  },
  {
    id: 7,
    title: "First Two Pages of Frankenstein",
    artist: "The National",
    year: "2023",
    imageString: "/firstTwoPagesOfFrankenstein.jpg",
  },
  {
    id: 8,
    title: "Five Days In July",
    artist: "Blue Rodeo",
    year: "1993",
    imageString: "/fiveDaysInJuly.jpg",
  },
  {
    id: 9,
    title: "i,i",
    artist: "Bon Iver",
    year: "2019",
    imageString: "/icommai.webp",
  },
  {
    id: 10,
    title: "Bon Iver, Bon Iver",
    artist: "Bon Iver",
    year: "2011",
    imageString: "/bonIverBonIver.jpg",
  },
  {
    id: 11,
    title: "Painkillers",
    artist: "Brian Fallon",
    year: "2016",
    imageString: "/painkillers.jpg",
  },
  {
    id: 12,
    title: "In These Silent Days",
    artist: "Brandi Carlile",
    year: "2021",
    imageString: "/inTheseSilentDays.png",
  },
  {
    id: 13,
    title: "Black Pumas",
    artist: "Black Pumas",
    year: "2019",
    imageString: "/blackPumas.png",
  },
  {
    id: 14,
    title: "Fleetwood Mac",
    artist: "Fleetwood Mac",
    year: "1975",
    imageString: "/fleetwoodMac.png",
  },
  {
    id: 15,
    title: "Folklore",
    artist: "Taylor Swift",
    year: "2020",
    imageString: "/folklore.png",
  },
  {
    id: 16,
    title: "Stick Season",
    artist: "Noah Kahan",
    year: "2022",
    imageString: "/stickSeason.webp",
  },
  {
    id: 17,
    title: "Unreal Unearth",
    artist: "Hozier",
    year: "2023",
    imageString: "/unrealUnearth.webp",
  },
  {
    id: 18,
    title: "Boxer",
    artist: "The National",
    year: "2007",
    imageString: "/boxer.jpg",
  },
  {
    id: 19,
    title: "Get Hurt",
    artist: "The Gaslight Anthem",
    year: "2014",
    imageString: "/getHurt.png",
  },
  {
    id: 20,
    title: "American Heartbreak",
    artist: "Zach Bryan",
    year: "2022",
    imageString: "/americanHeartbreak.webp",
  },
  {
    id: 21,
    title: "The Lumineers",
    artist: "The Lumineers",
    year: "2012",
    imageString: "/theLumineers.jpg",
  },
  {
    id: 22,
    title: "Serpentine Prison",
    artist: "Matt Berninger",
    year: "2020",
    imageString: "/serpentinePrison.png",
  },
  {
    id: 23,
    title: "Tearing At The Seams",
    artist: "Nathaniel Rateliff & The Night Sweats",
    year: "2018",
    imageString: "/tearingAtTheSeams.jpg",
  },
  {
    id: 24,
    title: "Brightside",
    artist: "The Lumineers",
    year: "2022",
    imageString: "/brightside.jpg",
  },
  {
    id: 25,
    title: "Handwritten",
    artist: "The Gaslight Anthem",
    year: "2012",
    imageString: "/handwritten.jpg",
  },
  {
    id: 26,
    title: "Self-titled",
    artist: "Marcus Mumford",
    year: "2022 ",
    imageString: "/selfTitled.jpeg",
  },
  {
    id: 27,
    title: "August and Everything After",
    artist: "Counting Crows",
    year: "1993",
    imageString: "/augustAndEverythingAfter.jpg",
  },
  {
    id: 28,
    title: "Original Hits",
    artist: "Barenaked Ladies",
    year: "2019",
    imageString: "/originalHits.webp",
  },
  {
    id: 29,
    title: "Jagged Little Pill",
    artist: "Alanis Morissette",
    year: "1995",
    imageString: "/jaggedLittlePill.jpg",
  },
  {
    id: 30,
    title: "22, A Million",
    artist: "Bon Iver",
    year: "2016",
    imageString: "/22AMillion.webp",
  },
  {
    id: 31,
    title: "Cracked Rear View",
    artist: "Hootie & the Blowfish",
    year: "1994",
    imageString: "/crackedRearView.jpg",
  },
  {
    id: 32,
    title: "Tracy Chapman",
    artist: "Tracy Chapman",
    year: "1988",
    imageString: "/tracyChapman.jpg",
  },
  {
    id: 33,
    title: "HELP!",
    artist: "The Beatles",
    year: "1965",
    imageString: "/help.png",
  },
  {
    id: 34,
    title: "Spirits Having Flown",
    artist: "Bee Gees",
    year: "1979",
    imageString: "/spiritsHavingFlown.jpg",
  },
  {
    id: 35,
    title: "The Future",
    artist: "Nathaniel Rateliff & The Night Sweats",
    year: "2021",
    imageString: "/theFuture.jpg",
  },
  {
    id: 36,
    title: "Blood Bank",
    artist: "Bon Iver",
    year: "2009",
    imageString: "/bloodBank.jpg",
  },
  {
    id: 37,
    title: "Surface Sounds",
    artist: "Kaleo",
    year: "2020",
    imageString: "/surfaceSounds.jpg",
  },
  {
    id: 38,
    title: "for Emma, forever ago",
    artist: "Bon Iver",
    year: "2008",
    imageString: "/forEmmaForeverAgo.webp",
  },
  {
    id: 39,
    title: "Punisher",
    artist: "Phoebe Bridgers",
    year: "2020",
    imageString: "/punisher.webp",
  },
  {
    id: 40,
    title: "Sleepwalkers",
    artist: "Brian Fallon",
    year: "2017",
    imageString: "/sleepwalkers.jpg",
  },
  {
    id: 41,
    title: "Orange Blood",
    artist: "Mt. Joy",
    year: "2022",
    imageString: "/orangeBlood.webp",
  },
  {
    id: 42,
    title: "ESP",
    artist: "Bee Gees",
    year: "1987",
    imageString: "/esp.jpg",
  },
  {
    id: 43,
    title: "Traveller",
    artist: "Chris Stapleton",
    year: "2015",
    imageString: "/traveller.webp",
  },
  {
    id: 44,
    title: "Threads",
    artist: "Sheryl Crow",
    year: "2019",
    imageString: "/threads.webp",
  },
  {
    id: 45,
    title: "A War on Everything",
    artist: "The Glorious Sons",
    year: "2019",
    imageString: "/aWarOnEverything.jpg",
  },
];
