import { RecordResultProps } from "./types";

export const recordResultsList: RecordResultProps[] = [
  {
    id: 1,
    title: "Alligator",
    artist: "The National",
    year: "2005",
    imageString: "/alligator.webp",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#AAC93F",
    innerColour: "#1A1919",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Matt Berninger, Aaron Dessner, Bryce Dessner, Scott Devendorf, Bryan Devendorf",
    description:
      "Breakout album for a band that just keeps producing - absolute classic",
    recordNumber: 3,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Secret Meeting" },
          { number: "02", title: "Karen" },
          { number: "03", title: "Lit Up" },
          { number: "04", title: "Looking for Astronauts" },
          { number: "05", title: "Daughters of the Soho Riots" },
          { number: "06", title: "Baby, We'll Be Fine" },
          { number: "07", title: "Friend of Mine" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "08", title: "Val Jester" },
          { number: "09", title: "All the Wine" },
          { number: "10", title: "Abel" },
          { number: "11", title: "The Geese of Beverly Road" },
          { number: "12", title: "City Middle" },
          { number: "13", title: "Mr. November" },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Wildflowers",
    artist: "I, the Mountain",
    year: "2025",
    imageString: "/wildflowers.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#128287",
    innerColour: "#FDD5AF",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Allison Dyjach, Matthew Lamers, Matthew Rappolt, Rory McLachlin",
    description:
      "A fun and colourful album from the Kitchener based teacher collective",
    recordNumber: 2,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Walls" },
          { number: "02", title: "Wildflowers" },
          { number: "03", title: "Carry On" },
          { number: "04", title: "{Don't Look Back}" },
          { number: "05", title: "Jillian" },
          { number: "06", title: "Wildfire" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "07", title: "Fade Away" },
          { number: "08", title: "Houseplant" },
          { number: "09", title: "Summer" },
          { number: "10", title: "Kings of Love" },
          { number: "11", title: "{She Went Away}" },
          { number: "12", title: "Coal Mine" },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Abbey Road",
    artist: "The Beatles",
    year: "1969",
    imageString: "/abbeyRoad.webp",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    innerColour: "#252323",
    recordHighlightColour: "#B6DBFE",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "John Lennon, Paul McCartney, George Harrison, Ringo Starr",
    description: "Iconic, timeless",
    recordNumber: 12,
    sides: [
      {
        side: "1",
        tracks: [
          { number: "01", title: "Come Together" },
          { number: "02", title: "Something" },
          { number: "03", title: "Maxwell's Silver Hammer" },
          { number: "04", title: "Oh! Darling" },
          { number: "05", title: "Octopus's Garden" },
          { number: "06", title: "I Want You (She's So Heavy)" },
        ],
      },
      {
        side: "2",
        tracks: [
          { number: "07", title: "Here Comes the Sun" },
          { number: "08", title: "Because" },
          { number: "09", title: "You Never Give Me Your Money" },
          { number: "10", title: "Sun King" },
          { number: "11", title: "Mean Mr. Mustard" },
          { number: "12", title: "Polythene Pam" },
          { number: "13", title: "She Came In Through the Bathroom Window" },
          { number: "14", title: "Golden Slumbers" },
          { number: "15", title: "Carry That Weight" },
          { number: "16", title: "The End" },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "By & By",
    artist: "Caamp",
    year: "2019",
    imageString: "/byAndBy.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#D1C4B3",
    innerColour: "#D1C4B3",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Taylor Meier, Evan Westfall, Matt Vinson",
    description:
      "An heartfelt collection of folk melodies that showcase Caamp's signature sound",
    recordNumber: 3,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Feels Like Home" },
          { number: "02", title: "Keep the Blues Away" },
          { number: "03", title: "No Sleep" },
          { number: "04", title: "Peach Fuzz" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "05", title: "Wolf Song" },
          { number: "06", title: "Penny, Heads Up" },
          { number: "07", title: "Wunderbar" },
          { number: "08", title: "On & On & On" },
        ],
      },
      {
        side: "C",
        tracks: [
          { number: "09", title: "Moonsmoke" },
          { number: "10", title: "Huckleberry Love" },
          { number: "11", title: "By and By" },
          { number: "12", title: "Of Love and Life" },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "South of Here",
    artist: "Nathaniel Rateliff & The Night Sweats",
    year: "2024",
    imageString: "/southOfHere.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#9487BF",
    innerColour: "#F7C13C",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Nathaniel Rateliff, Joseph Pope III, Luke Mossman, Mark Shusterman, Patrick Meese",
    description:
      "Written about a trip to Sonic Ranch to record the album, this record is a showcase of Rateliff's incredible songwriting talent",
    recordNumber: 4,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "David and Golaith" },
          { number: "02", title: "Heartless" },
          { number: "03", title: "Remember I Was a Dancer" },
          { number: "04", title: "Get Used to the Night" },
          { number: "05", title: "South of Here" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "06", title: "Everybody Wants Something" },
          { number: "07", title: "Center of Me" },
          { number: "08", title: "Cars in the Desert" },
          { number: "09", title: "I Would Like to Heal" },
          { number: "10", title: "Call Me (Whatever You Like)" },
          { number: "11", title: "Time Makes Fools Of Us All" },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Midnights",
    artist: "Taylor Swift",
    year: "2022",
    imageString: "/midnights.png",
    recordColour: "#173437",
    recordColourDescription: "Midnight Green",
    recordHighlightColour: "#729AAF",
    innerColour: "#EDEDEC",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Taylor Swift",
    description: "An effortless pop album from the master lyricist",
    recordNumber: 10,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Lavender Haze" },
          { number: "02", title: "Maroon" },
          { number: "03", title: "Anti-Hero" },
          { number: "04", title: "Snow on the Beach (Feat. Lana Del Ray)" },
          { number: "05", title: "You're on Your Own, Kid" },
          { number: "06", title: "Midnight Rain" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "07", title: "Question...?" },
          { number: "08", title: "Vigilante Shit" },
          { number: "09", title: "Bejeweled" },
          { number: "10", title: "Labyrinth" },
          { number: "11", title: "Karma" },
          { number: "12", title: "Sweet Nothing" },
          { number: "13", title: "Mastermind" },
        ],
      },
    ],
  },
  {
    id: 7,
    title: "First Two Pages of Frankenstein",
    artist: "The National",
    year: "2023",
    imageString: "/firstTwoPagesOfFrankenstein.jpg",
    recordColour: "#B00D3E",
    recordColourDescription: "Cherry Red",
    recordHighlightColour: "#D0B8C8",
    innerColour: "#DEDEDB",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Matt Berninger, Aaron Dessner, Bryce Dessner, Scott Devendorf, Bryan Devendorf",
    description:
      "Post-hiatus The National come back to prove why they are the indie rock kings",
    recordNumber: 9,
    sides: [
      {
        side: "1",
        tracks: [
          { number: "01", title: "Once Upon a Poolside" },
          { number: "02", title: "Eucalyptus" },
          { number: "03", title: "New Order T-Shirt" },
          { number: "04", title: "This Isn't Helping" },
          { number: "05", title: "Tropic Morning News" },
          { number: "06", title: "Alien" },
        ],
      },
      {
        side: "2",
        tracks: [
          { number: "07", title: "The Alcott" },
          { number: "08", title: "Grease in your Hair" },
          { number: "09", title: "Ice Machine" },
          { number: "10", title: "Your Mind Is Not Your Friend" },
          { number: "11", title: "Send for Me" },
        ],
      },
    ],
  },
  {
    id: 8,
    title: "Five Days In July",
    artist: "Blue Rodeo",
    year: "1993",
    imageString: "/fiveDaysInJuly.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#EC4F85",
    innerColour: "#3F375C",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Jim Cuddy, Greg Keelor, Bazil Donovan, Cleave Anderson",
    description:
      "A perfect blend of country and rock from one of Canada's greatest bands",
    recordNumber: 5,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "5 Days in May" },
          { number: "02", title: "Hasn't Hit Me Yet" },
          { number: "03", title: "Bad Timing" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "04", title: "Cynthia" },
          { number: "05", title: "Photographs" },
          { number: "06", title: "What Is This Love" },
        ],
      },
      {
        side: "C",
        tracks: [
          { number: "07", title: "English Bay" },
          { number: "08", title: "Head Over Heels" },
          { number: "09", title: "Til I Gain Control Again" },
        ],
      },
      {
        side: "D",
        tracks: [
          { number: "10", title: "Dark Angel" },
          { number: "11", title: "Kmow Where You Go/Tell Me Your Dream" },
        ],
      },
    ],
  },
  {
    id: 9,
    title: "i,i",
    artist: "Bon Iver",
    year: "2019",
    imageString: "/icommai.webp",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#D94A28",
    innerColour: "#CFCFC5",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Justin Vernon, Sean Carey, Matt McCaughan, Andrew Fitzpatrick, Mike Lewis",
    description:
      "A massive undertaking, this album pushes the Bon Iver style to its peak",
    recordNumber: 4,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Yi" },
          { number: "02", title: "iMi" },
          { number: "03", title: "We" },
          { number: "04", title: "Holyfields" },
          { number: "05", title: "Hey, Ma" },
          { number: "06", title: "U (Man Like)" },
          { number: "07", title: "Naeem" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "08", title: "Jelmore" },
          { number: "09", title: "Faith" },
          { number: "10", title: "Marion" },
          { number: "11", title: "Salem" },
          { number: "12", title: "Sh'Diah" },
          { number: "13", title: "RABi" },
        ],
      },
    ],
  },
  {
    id: 10,
    title: "Bon Iver, Bon Iver",
    artist: "Bon Iver",
    year: "2011",
    imageString: "/bonIverBonIver.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    innerColour: "#CB2D2F",
    recordHighlightColour: "#838755",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Mike Lewis, Colin Stetson, Mikey Noyce, Rob Moose, Justin Vernon, Matt McCaughan, Tom Winceck, Greg Leisz, Brian Joseph, Jim Shoemaker, CJ Camerieri",
    description:
      "Musically rich this album builds a rich nature filled world to get lost in",
    recordNumber: 2,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Perth" },
          { number: "02", title: "Minnesota, WI" },
          { number: "03", title: "Holocene" },
          { number: "04", title: "Towers" },
          { number: "05", title: "Michicant" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "06", title: "Hinnom, TX" },
          { number: "07", title: "Wash." },
          { number: "08", title: "Calgary" },
          { number: "09", title: "Lisbon, OH" },
          { number: "10", title: "Beth/Rest" },
        ],
      },
    ],
  },
  {
    id: 11,
    title: "Painkillers",
    artist: "Brian Fallon",
    year: "2016",
    imageString: "/painkillers.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    innerColour: "#E6DFD3",
    recordHighlightColour: "#60B2D8",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Brian Fallon",
    description:
      "An accoustic break from the Gaslight Anthem, this album showcases Fallon's songwriting in a more relaxed setting",
    recordNumber: 1,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "A Wonderful Life" },
          { number: "02", title: "Painkillers" },
          { number: "03", title: "Among Other Foolish Things" },
          { number: "04", title: "Smoke" },
          { number: "05", title: "Steve McQueen" },
          { number: "06", title: "Nobody Wins" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "07", title: "Rosemary" },
          { number: "08", title: "Red Lights" },
          { number: "09", title: "Long Drives" },
          { number: "10", title: "Honey Magnolia" },
          { number: "11", title: "Mojo Hand" },
          { number: "12", title: "Open All Night" },
        ],
      },
    ],
  },
  {
    id: 12,
    title: "In These Silent Days",
    artist: "Brandi Carlile",
    year: "2021",
    imageString: "/inTheseSilentDays.png",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    innerColour: "#005894",
    recordHighlightColour: "#16BEE0",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Brandi Carlile, Phil Hanseroth, Tim Hanseroth",
    description:
      "A powerful and emotional album that shows why Carlile is one of the best",
    recordNumber: 7,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Right on Time" },
          { number: "02", title: "You and Me on the Rock" },
          { number: "03", title: "This Time Tomorrow" },
          { number: "04", title: "Broken Horses" },
          { number: "05", title: "Letter to the Past" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "06", title: "Mama Werewolf" },
          { number: "07", title: "When You're Wrong" },
          { number: "08", title: "Stay Gentle" },
          { number: "09", title: "Sinners Saints and Fools" },
          { number: "10", title: "Throwing Good After Bad" },
        ],
      },
    ],
  },
  {
    id: 13,
    title: "Black Pumas",
    artist: "Black Pumas",
    year: "2019",
    imageString: "/blackPumas.png",
    recordColour: "#FFFFFF",
    recordColourDescription: "Simple White",
    innerColour: "#0C0C0C",
    recordHighlightColour: "#B93F2D",
    recordLineColour: "black",
    speed: "33 ⅓ RPM",
    musicians: "Eric Burton, Adrian Quesada",
    description:
      "A soulful but fresh sound, this debut album is perfectly balanced in its new style",
    recordNumber: 1,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Black Moon Rising" },
          { number: "02", title: "Colors" },
          { number: "03", title: "Know You Better" },
          { number: "04", title: "Fire" },
          { number: "05", title: "OCT 33" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "06", title: "Stay Gold" },
          { number: "07", title: "Old Man" },
          { number: "08", title: "Confines" },
          { number: "09", title: "Touch the Sky" },
          { number: "10", title: "Sweet Conversations" },
        ],
      },
    ],
  },
  {
    id: 14,
    title: "Fleetwood Mac",
    artist: "Fleetwood Mac",
    year: "1975",
    imageString: "/fleetwoodMac.png",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#CE9033",
    innerColour: "#CE9033",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Stevie Nicks, Lindsey Buckingham, Christine McVie, John McVie, Mick Fleetwood",
    description: "Rhiannon, Landslide - what more do you need",
    recordNumber: 10,
    sides: [
      {
        side: "One",
        tracks: [
          { number: "01", title: "Monday Morning" },
          { number: "02", title: "Warm Ways" },
          { number: "03", title: "Blue Letter" },
          { number: "04", title: "Rhiannon" },
          { number: "05", title: "Over My Head" },
          { number: "06", title: "Crystal" },
        ],
      },
      {
        side: "Two",
        tracks: [
          { number: "07", title: "Say You Love Me" },
          { number: "08", title: "Landslide" },
          { number: "09", title: "World Turning" },
          { number: "10", title: "Sugar Daddy" },
          { number: "11", title: "I'm So Afraid" },
        ],
      },
    ],
  },
  {
    id: 15,
    title: "Folklore",
    artist: "Taylor Swift",
    year: "2020",
    imageString: "/folklore.png",
    recordColour: "#8F7E67",
    recordColourDescription: "Earthly Fairytale",
    recordHighlightColour: "#DCDCDC",
    innerColour: "#DCDCDC",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Taylor Swift",
    description:
      "Her best album, in my humble opinion, this album was peak covid creativity",
    recordNumber: 8,
    sides: [
      {
        side: "1",
        tracks: [
          { number: "01", title: "the 1" },
          { number: "02", title: "cardigan" },
          { number: "03", title: "the last great american dynasty" },
          { number: "04", title: "exile (feat. Bon Iver)" },
        ],
      },
      {
        side: "2",
        tracks: [
          { number: "05", title: "my tears ricochet" },
          { number: "06", title: "mirrorball" },
          { number: "07", title: "seven" },
          { number: "08", title: "august" },
          { number: "09", title: "this is me trying" },
        ],
      },
      {
        side: "3",
        tracks: [
          { number: "10", title: "illicit affairs" },
          { number: "11", title: "invisible string" },
          { number: "12", title: "mad woman" },
          { number: "13", title: "epiphany" },
        ],
      },
      {
        side: "4",
        tracks: [
          { number: "14", title: "betty" },
          { number: "15", title: "peace" },
          { number: "16", title: "hoax" },
          { number: "17", title: "the lakes" },
        ],
      },
    ],
  },
  {
    id: 16,
    title: "Stick Season",
    artist: "Noah Kahan",
    year: "2022",
    imageString: "/stickSeason.webp",
    recordColour: "#251F1F",
    recordColourDescription: "Woodsy Brown",
    recordHighlightColour: "#8A6B58",
    innerColour: "#D4C0A6",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Noah Kahan",
    description:
      "A huge album, defining Kahan's signature New England folk sound",
    recordNumber: 3,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Northern Attitude" },
          { number: "02", title: "Stick Season" },
          { number: "03", title: "All My Love" },
          { number: "04", title: "She Calls Me Back" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "05", title: "Come Over" },
          { number: "06", title: "New Perspective" },
          { number: "07", title: "Everywhere, Everything" },
        ],
      },
      {
        side: "C",
        tracks: [
          { number: "08", title: "Orange Juice" },
          { number: "09", title: "Strawberry Wine" },
          { number: "10", title: "Growing Sideways" },
          { number: "11", title: "Halloween" },
        ],
      },
      {
        side: "D",
        tracks: [
          { number: "12", title: "Homesick" },
          { number: "13", title: "Still" },
          { number: "14", title: "The View Between Villages" },
        ],
      },
      {
        side: "E",
        tracks: [
          { number: "15", title: "Your Needs, My Needs" },
          { number: "16", title: "Dial Drunk" },
          { number: "17", title: "Paul Revere" },
          { number: "18", title: "No Complaints" },
        ],
      },
      {
        side: "F",
        tracks: [
          { number: "19", title: "Call Your Mom" },
          { number: "20", title: "You're Gonna Go Far" },
          { number: "21", title: "The View Between Villages (Extended)" },
        ],
      },
    ],
  },
  {
    id: 17,
    title: "Unreal Unearth",
    artist: "Hozier",
    year: "2023",
    imageString: "/unrealUnearth.webp",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#C6985B",
    innerColour: "#C6985B",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Andrew Hozier-Byrne",
    description:
      "Part fairy tale, part booming anthem, this album weaves through multiple languages and sounds effortlessly",
    recordNumber: 3,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "De Selby (Part 1)" },
          { number: "02", title: "De Selby (Part 2)" },
          { number: "03", title: "First Time" },
          { number: "04", title: "Francesca" },
          { number: "05", title: "I, Carrion (Icarian)" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "06", title: "Eat Your Young" },
          { number: "07", title: "Damage Gets Done (ft. Brandi Carlile)" },
          { number: "08", title: "Who We Are" },
        ],
      },
      {
        side: "C",
        tracks: [
          { number: "09", title: "Son of Nyx" },
          { number: "10", title: "All Things End" },
          {
            number: "11",
            title: "To Someone From A Warm Climate (UISCEFHUAREITHE)",
          },
          { number: "12", title: "Butchered Tongue" },
        ],
      },
      {
        side: "D",
        tracks: [
          { number: "13", title: "Anything But" },
          { number: "14", title: "Abstract (Pyschopomp)" },
          { number: "15", title: "Unknown, Nth" },
        ],
      },
    ],
  },
  {
    id: 18,
    title: "Boxer",
    artist: "The National",
    year: "2007",
    imageString: "/boxer.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#FDF202",
    innerColour: "#252323",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians:
      "Matt Berninger, Aaron Dessner, Bryce Dessner, Scott Devendorf, Bryan Devendorf",
    description:
      "Big and brooding, this album is relentless in its emotional depth and sonic beauty",
    recordNumber: 4,
    sides: [
      {
        side: "1",
        tracks: [
          { number: "01", title: "Fake Empire" },
          { number: "02", title: "Mistaken for Strangers" },
          { number: "03", title: "Brainy" },
          { number: "04", title: "Squalor Victoria" },
          { number: "05", title: "Green Gloves" },
          { number: "06", title: "Slow Show" },
        ],
      },
      {
        side: "2",
        tracks: [
          { number: "07", title: "Apartment Story" },
          { number: "08", title: "Start a War" },
          { number: "09", title: "Guest Room" },
          { number: "10", title: "Racing Like a Pro" },
          { number: "11", title: "Ada" },
          { number: "12", title: "Gospel" },
        ],
      },
    ],
  },
  // {
  //   id: 19,
  //   title: "Get Hurt",
  //   artist: "The Gaslight Anthem",
  //   year: "2014",
  //   imageString: "/getHurt.png",
  // },
  {
    id: 20,
    title: "American Heartbreak",
    artist: "Zach Bryan",
    year: "2022",
    imageString: "/americanHeartbreak.webp",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    recordHighlightColour: "#9D8369",
    innerColour: "#F4F4DE",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Zach Bryan ",
    description:
      "Expansive album with a big country sound and heartfelt lyrics",
    recordNumber: 3,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Late July" },
          { number: "02", title: "Something in the Orange Z&E" },
          { number: "03", title: "Heavy Eyes" },
          { number: "04", title: "Mine Again" },
          { number: "05", title: "Happy Instead" },
          { number: "06", title: "Right Now the Best" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "07", title: "The Outskirts" },
          { number: "08", title: "Younger Years" },
          { number: "09", title: "Cold Damn Vampires" },
          { number: "10", title: "Tishomingo" },
          { number: "11", title: "She's Alright" },
          { number: "12", title: "You are My Sunshine" },
        ],
      },
      {
        side: "C",
        tracks: [
          { number: "13", title: "Darling" },
          { number: "14", title: "Ninth Cloud" },
          { number: "15", title: "Oklahoma City" },
          { number: "16", title: "Sun to Me" },
          { number: "17", title: "Highway Boys" },
          { number: "18", title: "Whiskey Fever" },
        ],
      },
      {
        side: "D",
        tracks: [
          { number: "19", title: "Billy Stay" },
          { number: "20", title: "Sober Side of Sorry" },
          { number: "21", title: "High Beams" },
          { number: "22", title: "The Good I'll Do" },
          { number: "23", title: "Someday (Maggie's)" },
        ],
      },
      {
        side: "E",
        tracks: [
          { number: "24", title: "Poems and Closing Time" },
          { number: "25", title: "From Austin" },
          { number: "26", title: "If She Wants a Cowboy" },
          { number: "27", title: "Corinthians (Proctor's)" },
          { number: "28", title: "Open the Gates" },
          { number: "29", title: "Half Grown" },
        ],
      },
      {
        side: "F",
        tracks: [
          { number: "30", title: "No Cure" },
          { number: "31", title: "'68 Fastback" },
          { number: "32", title: "Blue" },
          { number: "33", title: "Morning Time" },
          { number: "34", title: "This Road I Know" },
        ],
      },
    ],
  },
  // {
  //   id: 21,
  //   title: "The Lumineers",
  //   artist: "The Lumineers",
  //   year: "2012",
  //   imageString: "/theLumineers.jpg",
  // },
  // {
  //   id: 22,
  //   title: "Serpentine Prison",
  //   artist: "Matt Berninger",
  //   year: "2020",
  //   imageString: "/serpentinePrison.png",
  // },
  // {
  //   id: 23,
  //   title: "Tearing At The Seams",
  //   artist: "Nathaniel Rateliff & The Night Sweats",
  //   year: "2018",
  //   imageString: "/tearingAtTheSeams.jpg",
  // },
  // {
  //   id: 24,
  //   title: "Brightside",
  //   artist: "The Lumineers",
  //   year: "2022",
  //   imageString: "/brightside.jpg",
  // },
  // {
  //   id: 25,
  //   title: "Handwritten",
  //   artist: "The Gaslight Anthem",
  //   year: "2012",
  //   imageString: "/handwritten.jpg",
  // },
  // {
  //   id: 26,
  //   title: "Self-titled",
  //   artist: "Marcus Mumford",
  //   year: "2022 ",
  //   imageString: "/selfTitled.jpeg",
  // },
  // {
  //   id: 27,
  //   title: "August and Everything After",
  //   artist: "Counting Crows",
  //   year: "1993",
  //   imageString: "/augustAndEverythingAfter.jpg",
  // },
  // {
  //   id: 28,
  //   title: "Original Hits",
  //   artist: "Barenaked Ladies",
  //   year: "2019",
  //   imageString: "/originalHits.webp",
  // },
  // {
  //   id: 29,
  //   title: "Jagged Little Pill",
  //   artist: "Alanis Morissette",
  //   year: "1995",
  //   imageString: "/jaggedLittlePill.jpg",
  // },
  // {
  //   id: 30,
  //   title: "22, A Million",
  //   artist: "Bon Iver",
  //   year: "2016",
  //   imageString: "/22AMillion.webp",
  // },
  {
    id: 31,
    title: "Cracked Rear View",
    artist: "Hootie & the Blowfish",
    year: "1994",
    imageString: "/crackedRearView.jpg",
    recordColour: "#000000",
    recordColourDescription: "Classic Black",
    innerColour: "#252323",
    recordHighlightColour: "#C13D48",
    recordLineColour: "white",
    speed: "33 ⅓ RPM",
    musicians: "Darius Rucker, Mark Bryan, Dean Felber, Jim Sonefeld",
    description:
      "Absolutely timeless album that will have you dancing to every track",
    recordNumber: 1,
    sides: [
      {
        side: "A",
        tracks: [
          { number: "01", title: "Hannah Jane" },
          { number: "02", title: "Hold My Hand" },
          { number: "03", title: "Let Her Cry" },
          { number: "04", title: "Only Wanna Be with You" },
          { number: "05", title: "Running from an Angel" },
          { number: "06", title: "I'm Goin' Home" },
        ],
      },
      {
        side: "B",
        tracks: [
          { number: "07", title: "Drowning" },
          { number: "08", title: "Time" },
          { number: "09", title: "Look Away" },
          { number: "10", title: "Not Even the Trees" },
          { number: "11", title: "Goodbye" },
        ],
      },
    ],
  },
  // {
  //   id: 32,
  //   title: "Tracy Chapman",
  //   artist: "Tracy Chapman",
  //   year: "1988",
  //   imageString: "/tracyChapman.jpg",
  // },
  // {
  //   id: 33,
  //   title: "HELP!",
  //   artist: "The Beatles",
  //   year: "1965",
  //   imageString: "/help.png",
  // },
  // {
  //   id: 34,
  //   title: "Spirits Having Flown",
  //   artist: "Bee Gees",
  //   year: "1979",
  //   imageString: "/spiritsHavingFlown.jpg",
  // },
  // {
  //   id: 35,
  //   title: "The Future",
  //   artist: "Nathaniel Rateliff & The Night Sweats",
  //   year: "2021",
  //   imageString: "/theFuture.jpg",
  // },
  // {
  //   id: 36,
  //   title: "Blood Bank",
  //   artist: "Bon Iver",
  //   year: "2009",
  //   imageString: "/bloodBank.jpg",
  // },
  // {
  //   id: 37,
  //   title: "Surface Sounds",
  //   artist: "Kaleo",
  //   year: "2020",
  //   imageString: "/surfaceSounds.jpg",
  // },
  // {
  //   id: 38,
  //   title: "for Emma, forever ago",
  //   artist: "Bon Iver",
  //   year: "2008",
  //   imageString: "/forEmmaForeverAgo.webp",
  // },
  // {
  //   id: 39,
  //   title: "Punisher",
  //   artist: "Phoebe Bridgers",
  //   year: "2020",
  //   imageString: "/punisher.webp",
  // },
  // {
  //   id: 40,
  //   title: "Sleepwalkers",
  //   artist: "Brian Fallon",
  //   year: "2017",
  //   imageString: "/sleepwalkers.jpg",
  // },
  // {
  //   id: 41,
  //   title: "Orange Blood",
  //   artist: "Mt. Joy",
  //   year: "2022",
  //   imageString: "/orangeBlood.webp",
  // },
  // {
  //   id: 42,
  //   title: "ESP",
  //   artist: "Bee Gees",
  //   year: "1987",
  //   imageString: "/esp.jpg",
  // },
  // {
  //   id: 43,
  //   title: "Traveller",
  //   artist: "Chris Stapleton",
  //   year: "2015",
  //   imageString: "/traveller.webp",
  // },
  // {
  //   id: 44,
  //   title: "Threads",
  //   artist: "Sheryl Crow",
  //   year: "2019",
  //   imageString: "/threads.webp",
  // },
  // {
  //   id: 45,
  //   title: "A War on Everything",
  //   artist: "The Glorious Sons",
  //   year: "2019",
  //   imageString: "/aWarOnEverything.jpg",
  // },
  // {
  //   id: 46,
  //   title: "No Hard Feelings",
  //   artist: "The Beaches",
  //   year: "2025",
  //   imageString: "/noHardFeelings.jpg",
  //   recordColour: "#DDE7EE",
  //   recordColourDescription: "Mystic Blue Waves",
  //   recordHighlightColour: "#E4E7EE",
  //   innerColour: "#1A141F",
  //   recordLineColour: "black",
  //   speed: "33 ⅓ RPM",
  //   musicians:
  //     "Jordan Miller, Kylie Miller, Leandra Earl, Eliza Enman-McDaniel",
  //   description: "Loud and proud rock album from Toronto's finest",
  //   recordNumber: 3,
  //   sides: [
  //     {
  //       side: "A",
  //       tracks: [
  //         { number: "01", title: "Can I Call You in the Morning?" },
  //         { number: "02", title: "Did I Say Too Much" },
  //         { number: "03", title: "Sorry For Your Loss" },
  //         { number: "04", title: "Touch Myself" },
  //         { number: "05", title: "Fine, Let's Get Married" },
  //         { number: "06", title: "Takes One to Know One" },
  //       ],
  //     },
  //     {
  //       side: "B",
  //       tracks: [
  //         { number: "07", title: "I Wore You Better" },
  //         { number: "08", title: "Dirty Laundry" },
  //         { number: "09", title: "Lesbian of the Year" },
  //         { number: "10", title: "Jocelyn" },
  //         { number: "11", title: "Last Girls at the Party" },
  //       ],
  //     },
  //   ],
  // },
];
